CC = gcc
CFLAGS = -Wall -g
BIN = bin/

all:exo2 exo3	exo4 exo5 


exo2: exo2.c
	$(CC) -o $@ $< $(CFLAGS)

exo3: exo3.c
	$(CC) -o $@ $< $(CFLAGS)

exo4: exo4.c
	$(CC) -o $@ $< $(CFLAGS)

exo5: exo5.c
	$(CC) -o $@ $< $(CFLAGS) 

