package Comptes;


/**
* Comptes/ComptePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* lundi 11 novembre 2013 21 h 27 CET
*/

public abstract class ComptePOA extends org.omg.PortableServer.Servant
 implements Comptes.CompteOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deposeBillets", new java.lang.Integer (0));
    _methods.put ("retireBillets", new java.lang.Integer (1));
    _methods.put ("afficheMontant", new java.lang.Integer (2));
    _methods.put ("virementCompteaCompte", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  //readonly attribute float solde;
       case 0:  // Comptes/Compte/deposeBillets
       {
         float depot = in.read_float ();
         this.deposeBillets (depot);
         out = $rh.createReply();
         break;
       }

       case 1:  // Comptes/Compte/retireBillets
       {
         float retrait = in.read_float ();
         boolean $result = false;
         $result = this.retireBillets (retrait);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Comptes/Compte/afficheMontant
       {
         float $result = (float)0;
         $result = this.afficheMontant ();
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 3:  // Comptes/Compte/virementCompteaCompte
       {
         float somme = in.read_float ();
         Comptes.Compte destinataire = Comptes.CompteHelper.read (in);
         boolean $result = false;
         $result = this.virementCompteaCompte (somme, destinataire);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Comptes/Compte:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Compte _this() 
  {
    return CompteHelper.narrow(
    super._this_object());
  }

  public Compte _this(org.omg.CORBA.ORB orb) 
  {
    return CompteHelper.narrow(
    super._this_object(orb));
  }


} // class ComptePOA
