package Comptes;


/**
* Comptes/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* lundi 11 novembre 2013 21 h 27 CET
*/

public interface Compte extends CompteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compte
