package Comptes;


/**
* Comptes/CompteHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* lundi 11 novembre 2013 21 h 27 CET
*/

abstract public class CompteHelper
{
  private static String  _id = "IDL:Comptes/Compte:1.0";

  public static void insert (org.omg.CORBA.Any a, Comptes.Compte that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Comptes.Compte extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Comptes.CompteHelper.id (), "Compte");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Comptes.Compte read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CompteStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Comptes.Compte value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Comptes.Compte narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Comptes.Compte)
      return (Comptes.Compte)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Comptes._CompteStub stub = new Comptes._CompteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Comptes.Compte unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Comptes.Compte)
      return (Comptes.Compte)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Comptes._CompteStub stub = new Comptes._CompteStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
