package Comptes;

/**
* Comptes/CompteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* lundi 11 novembre 2013 15 h 10 CET
*/

public final class CompteHolder implements org.omg.CORBA.portable.Streamable
{
  public Comptes.Compte value = null;

  public CompteHolder ()
  {
  }

  public CompteHolder (Comptes.Compte initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Comptes.CompteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Comptes.CompteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Comptes.CompteHelper.type ();
  }

}
