package Comptes;


/**
* Comptes/CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* lundi 11 novembre 2013 15 h 10 CET
*/

public interface CompteOperations 
{

  //readonly attribute float solde;
  void deposeBillets (float depot);
  boolean retireBillets (float retrait);
  float afficheMontant ();
  boolean virementCompteaCompte (float somme, Comptes.Compte destinataire);
} // interface CompteOperations
