
/**
* CompteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compte.idl
* mardi 5 novembre 2013 11 h 44 CET
*/

public interface CompteOperations 
{

  //long solde;
  float solde ();
  void deposeBillets (float depot);
  boolean retireBillets (float retrait);
  float afficheMontant ();
} // interface CompteOperations
