CC = gcc
CFLAGS = -Wall -g
BIN = bin/

all:exo2 exo4 

#exo1: exo1.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

exo2: exo2.c
	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo2b: exo2b.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo3: exo3.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

exo4: exo4.c
	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo4b: exo4b.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo5: exo5.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo6: exo6.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo6b: exo6b.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo7: exo7.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

#exo8: exo8.c
#	$(CC) -o $(BIN)$@ $< $(CFLAGS)

