
/**
* IcarreHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* dimanche 10 novembre 2013 18 h 22 CET
*/

public final class IcarreHolder implements org.omg.CORBA.portable.Streamable
{
  public Icarre value = null;

  public IcarreHolder ()
  {
  }

  public IcarreHolder (Icarre initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IcarreHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IcarreHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IcarreHelper.type ();
  }

}
