
/**
* Icarre.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* dimanche 10 novembre 2013 18 h 22 CET
*/

public interface Icarre extends IcarreOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Icarre
