
/**
* _IcarreStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* dimanche 10 novembre 2013 18 h 30 CET
*/

public class _IcarreStub extends org.omg.CORBA.portable.ObjectImpl implements Icarre
{

  public void carre (int source, org.omg.CORBA.IntHolder result)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("carre", true);
                $out.write_long (source);
                $in = _invoke ($out);
                result.value = $in.read_long ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                carre (source, result        );
            } finally {
                _releaseReply ($in);
            }
  } // carre

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Icarre:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _IcarreStub
