
/**
* IcarrePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* dimanche 10 novembre 2013 18 h 30 CET
*/

public abstract class IcarrePOA extends org.omg.PortableServer.Servant
 implements IcarreOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("carre", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Icarre/carre
       {
         int source = in.read_long ();
         org.omg.CORBA.IntHolder result = new org.omg.CORBA.IntHolder ();
         this.carre (source, result);
         out = $rh.createReply();
         out.write_long (result.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Icarre:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Icarre _this() 
  {
    return IcarreHelper.narrow(
    super._this_object());
  }

  public Icarre _this(org.omg.CORBA.ORB orb) 
  {
    return IcarreHelper.narrow(
    super._this_object(orb));
  }


} // class IcarrePOA
