
/**
* IcarreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* dimanche 10 novembre 2013 18 h 30 CET
*/

public interface IcarreOperations 
{
  void carre (int source, org.omg.CORBA.IntHolder result);
} // interface IcarreOperations
