
/**
* AnnuaireOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* lundi 11 novembre 2013 12 h 43 CET
*/

public interface AnnuaireOperations 
{
  void chercheNom (String nom, org.omg.CORBA.StringHolder numero);
  void listerNoms (org.omg.CORBA.StringHolder liste);
  void ajouteNom (String nom, String num);
  void enleveNom (String nom);
} // interface AnnuaireOperations
