
/**
* AnnuaireHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* lundi 11 novembre 2013 12 h 43 CET
*/

abstract public class AnnuaireHelper
{
  private static String  _id = "IDL:Annuaire:1.0";

  public static void insert (org.omg.CORBA.Any a, Annuaire that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Annuaire extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AnnuaireHelper.id (), "Annuaire");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Annuaire read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AnnuaireStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Annuaire value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Annuaire narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Annuaire)
      return (Annuaire)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AnnuaireStub stub = new _AnnuaireStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Annuaire unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Annuaire)
      return (Annuaire)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _AnnuaireStub stub = new _AnnuaireStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
