
/**
* Annuaire.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* lundi 11 novembre 2013 12 h 43 CET
*/

public interface Annuaire extends AnnuaireOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Annuaire
