
/**
* AnnuairePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* lundi 11 novembre 2013 12 h 43 CET
*/

public abstract class AnnuairePOA extends org.omg.PortableServer.Servant
 implements AnnuaireOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("chercheNom", new java.lang.Integer (0));
    _methods.put ("listerNoms", new java.lang.Integer (1));
    _methods.put ("ajouteNom", new java.lang.Integer (2));
    _methods.put ("enleveNom", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Annuaire/chercheNom
       {
         String nom = in.read_string ();
         org.omg.CORBA.StringHolder numero = new org.omg.CORBA.StringHolder ();
         this.chercheNom (nom, numero);
         out = $rh.createReply();
         out.write_string (numero.value);
         break;
       }

       case 1:  // Annuaire/listerNoms
       {
         org.omg.CORBA.StringHolder liste = new org.omg.CORBA.StringHolder ();
         this.listerNoms (liste);
         out = $rh.createReply();
         out.write_string (liste.value);
         break;
       }

       case 2:  // Annuaire/ajouteNom
       {
         String nom = in.read_string ();
         String num = in.read_string ();
         this.ajouteNom (nom, num);
         out = $rh.createReply();
         break;
       }

       case 3:  // Annuaire/enleveNom
       {
         String nom = in.read_string ();
         this.enleveNom (nom);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Annuaire:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Annuaire _this() 
  {
    return AnnuaireHelper.narrow(
    super._this_object());
  }

  public Annuaire _this(org.omg.CORBA.ORB orb) 
  {
    return AnnuaireHelper.narrow(
    super._this_object(orb));
  }


} // class AnnuairePOA
