const string iorfile = "annu.ior";
interface Annuaire {
  void chercheNom(in string nom, out string numero);
  void listerNoms(out string liste);
  void ajouteNom(in string nom,in string num);
  void enleveNom(in string nom);
};

