
/**
* iorfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Annuaire.idl
* lundi 11 novembre 2013 12 h 43 CET
*/

public interface iorfile
{
  public static final String value = "annu.ior";
}
