package Callback;


/**
* Callback/_CalculantStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

public class _CalculantStub extends org.omg.CORBA.portable.ObjectImpl implements Callback.Calculant
{

  public void faitLeCalcul (double val, Callback.Afficheur peer)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("faitLeCalcul", false);
                $out.write_double (val);
                Callback.AfficheurHelper.write ($out, peer);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                faitLeCalcul (val, peer        );
            } finally {
                _releaseReply ($in);
            }
  } // faitLeCalcul

  public void inscription (Callback.Afficheur peer)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("inscription", false);
                Callback.AfficheurHelper.write ($out, peer);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                inscription (peer        );
            } finally {
                _releaseReply ($in);
            }
  } // inscription

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Callback/Calculant:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _CalculantStub
