package Callback;


/**
* Callback/AfficheurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

public abstract class AfficheurPOA extends org.omg.PortableServer.Servant
 implements Callback.AfficheurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("afficheRes", new java.lang.Integer (0));
    _methods.put ("arreteORB", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Callback/Afficheur/afficheRes
       {
         String res = in.read_string ();
         this.afficheRes (res);
         out = $rh.createReply();
         break;
       }

       case 1:  // Callback/Afficheur/arreteORB
       {
         this.arreteORB ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Callback/Afficheur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Afficheur _this() 
  {
    return AfficheurHelper.narrow(
    super._this_object());
  }

  public Afficheur _this(org.omg.CORBA.ORB orb) 
  {
    return AfficheurHelper.narrow(
    super._this_object(orb));
  }


} // class AfficheurPOA
