package Callback;


/**
* Callback/AfficheurHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

abstract public class AfficheurHelper
{
  private static String  _id = "IDL:Callback/Afficheur:1.0";

  public static void insert (org.omg.CORBA.Any a, Callback.Afficheur that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Callback.Afficheur extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Callback.AfficheurHelper.id (), "Afficheur");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Callback.Afficheur read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AfficheurStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Callback.Afficheur value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Callback.Afficheur narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Callback.Afficheur)
      return (Callback.Afficheur)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Callback._AfficheurStub stub = new Callback._AfficheurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Callback.Afficheur unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Callback.Afficheur)
      return (Callback.Afficheur)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Callback._AfficheurStub stub = new Callback._AfficheurStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
