package Callback;


/**
* Callback/Afficheur.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

public interface Afficheur extends AfficheurOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Afficheur
