package Callback;


/**
* Callback/AfficheurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

public interface AfficheurOperations 
{
  void afficheRes (String res);
  void arreteORB ();
} // interface AfficheurOperations
