package Callback;

/**
* Callback/AfficheurHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

public final class AfficheurHolder implements org.omg.CORBA.portable.Streamable
{
  public Callback.Afficheur value = null;

  public AfficheurHolder ()
  {
  }

  public AfficheurHolder (Callback.Afficheur initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Callback.AfficheurHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Callback.AfficheurHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Callback.AfficheurHelper.type ();
  }

}
