package Callback;


/**
* Callback/CalculantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

public interface CalculantOperations 
{
  void faitLeCalcul (double val, Callback.Afficheur peer);
  void inscription (Callback.Afficheur peer);
} // interface CalculantOperations
