package Callback;

/**
* Callback/CalculantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Callback.idl
* mardi 12 novembre 2013 10 h 51 CET
*/

public final class CalculantHolder implements org.omg.CORBA.portable.Streamable
{
  public Callback.Calculant value = null;

  public CalculantHolder ()
  {
  }

  public CalculantHolder (Callback.Calculant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Callback.CalculantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Callback.CalculantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Callback.CalculantHelper.type ();
  }

}
