
CC = gcc
CFLAGS = -Wall -g
BIN = bin/

all:exo1 exo2 exo2b exo3 exo4 exo6   


exo1: exo1.c
	$(CC) -o $@ $< $(CFLAGS)

exo2: exo2.c
	$(CC) -o $@ $< $(CFLAGS)

exo2b: exo2b.c
	$(CC) -o $@ $< $(CFLAGS)

exo3: exo3.c
	$(CC) -o $@ $< $(CFLAGS)

exo4: exo4.c
	$(CC) -o $@ $< $(CFLAGS)

exo6: exo6.c
	$(CC) -o $@ $< $(CFLAGS)
