
CC = gcc
CFLAGS = -Wall -g
BIN = bin/

all:exo1 exo2 exo2b exo3 exo4 exo5 exo5b exo7 


exo1: exo1.c
	$(CC) -o $@ $< $(CFLAGS)

exo2: exo2.c
	$(CC) -o $@ $< $(CFLAGS)

exo2b: exo2b.c
	$(CC) -o $@ $< $(CFLAGS)

exo3: exo3.c
	$(CC) -o $@ $< $(CFLAGS)

exo4: exo4.c
	$(CC) -o $@ $< $(CFLAGS)

exo5: exo5.c
	$(CC) -o $@ $< $(CFLAGS)

exo5b: exo5b.c 
	$(CC) -o $@ $^ $(CFLAGS)

exo7: exo7.c 
	$(CC) -o $@ $^ $(CFLAGS)
