package OpMatricePackage;


/**
* OpMatricePackage/illegalMatriceMultiplication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* lundi 11 novembre 2013 11 h 27 CET
*/

public final class illegalMatriceMultiplication extends org.omg.CORBA.UserException
{

  public illegalMatriceMultiplication ()
  {
    super(illegalMatriceMultiplicationHelper.id());
  } // ctor


  public illegalMatriceMultiplication (String $reason)
  {
    super(illegalMatriceMultiplicationHelper.id() + "  " + $reason);
  } // ctor

} // class illegalMatriceMultiplication
