package OpMatricePackage;

/**
* OpMatricePackage/illegalMatriceMultiplicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* lundi 11 novembre 2013 11 h 27 CET
*/

public final class illegalMatriceMultiplicationHolder implements org.omg.CORBA.portable.Streamable
{
  public OpMatricePackage.illegalMatriceMultiplication value = null;

  public illegalMatriceMultiplicationHolder ()
  {
  }

  public illegalMatriceMultiplicationHolder (OpMatricePackage.illegalMatriceMultiplication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = OpMatricePackage.illegalMatriceMultiplicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    OpMatricePackage.illegalMatriceMultiplicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return OpMatricePackage.illegalMatriceMultiplicationHelper.type ();
  }

}
