
/**
* _OpMatriceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* lundi 11 novembre 2013 11 h 27 CET
*/

public class _OpMatriceStub extends org.omg.CORBA.portable.ObjectImpl implements OpMatrice
{

  public int[][] multiplicationMatrice (int[][] a, int[][] b) throws OpMatricePackage.illegalMatriceMultiplication
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("multiplicationMatrice", true);
                MatriceHelper.write ($out, a);
                MatriceHelper.write ($out, b);
                $in = _invoke ($out);
                int $result[][] = MatriceHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:OpMatrice/illegalMatriceMultiplication:1.0"))
                    throw OpMatricePackage.illegalMatriceMultiplicationHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return multiplicationMatrice (a, b        );
            } finally {
                _releaseReply ($in);
            }
  } // multiplicationMatrice

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OpMatrice:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _OpMatriceStub
