
/**
* iorfile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* lundi 11 novembre 2013 11 h 27 CET
*/

public interface iorfile
{
  public static final String value = "annu.ior";
}
