
/**
* MatriceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* lundi 11 novembre 2013 11 h 27 CET
*/

public final class MatriceHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[][] = null;

  public MatriceHolder ()
  {
  }

  public MatriceHolder (int[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatriceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatriceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatriceHelper.type ();
  }

}
