
/**
* OpMatricePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* lundi 11 novembre 2013 11 h 27 CET
*/

public abstract class OpMatricePOA extends org.omg.PortableServer.Servant
 implements OpMatriceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("multiplicationMatrice", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // OpMatrice/multiplicationMatrice
       {
         try {
           int a[][] = MatriceHelper.read (in);
           int b[][] = MatriceHelper.read (in);
           int $result[][] = null;
           $result = this.multiplicationMatrice (a, b);
           out = $rh.createReply();
           MatriceHelper.write (out, $result);
         } catch (OpMatricePackage.illegalMatriceMultiplication $ex) {
           out = $rh.createExceptionReply ();
           OpMatricePackage.illegalMatriceMultiplicationHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:OpMatrice:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public OpMatrice _this() 
  {
    return OpMatriceHelper.narrow(
    super._this_object());
  }

  public OpMatrice _this(org.omg.CORBA.ORB orb) 
  {
    return OpMatriceHelper.narrow(
    super._this_object(orb));
  }


} // class OpMatricePOA
