
/**
* OpMatrice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OpMatrice.idl
* lundi 11 novembre 2013 11 h 27 CET
*/

public interface OpMatrice extends OpMatriceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OpMatrice
