
/**
* IcarreOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Icarre.idl
* dimanche 10 novembre 2013 18 h 16 CET
*/

public interface IcarreOperations 
{
  int carre (int source);
} // interface IcarreOperations
